import nodemailer from "nodemailer";

// ======================================================
// TRANSPORTER (lazily created after dotenv.config() has run)
// ======================================================
let _transporter;

function getTransporter() {
  if (!_transporter) {
    _transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "mail.eftech.com.my",
      port: Number(process.env.SMTP_PORT) || 465,
      secure: Number(process.env.SMTP_PORT) === 465,
      ...(process.env.EMAIL_USER ? {
        auth: {
          user: process.env.EMAIL_USER,
          pass: process.env.EMAIL_PASS,
        },
      } : {}),
    });
    _transporter.verify((err) => {
      if (err) console.error("SMTP connection error:", err.message);
      else console.log("SMTP server ready");
    });
  }
  return _transporter;
}

// ======================================================
// CONSTANTS
// ======================================================
const BASE_URL = process.env.APP_URL || "https://myleave.edsdata.com.my";
const LOGO_EFTECH = `${BASE_URL}/static/images/eftech.logo.png`;
const LOGO_MYLEAVE = `${BASE_URL}/static/images/myleave.logo.png`;

const BRAND = {
  primary: "#49bdb3",
  primaryDark: "#38948e",
  navy: "#0c4a6e",
  bg: "#f5f7fb",
  surface: "#ffffff",
  text: "#0f172a",
  textSecondary: "#374151",
  muted: "#6b7280",
  mutedLight: "#9ca3af",
  border: "#e5e7eb",
  green: "#22c55e",
  greenBg: "#f0fdf4",
  greenBorder: "#bbf7d0",
  greenText: "#166534",
  red: "#ef4444",
  redBg: "#fef2f2",
  redBorder: "#fecaca",
  redText: "#991b1b",
  amber: "#f59e0b",
  amberBg: "#fffbeb",
  amberBorder: "#fde68a",
  amberText: "#92400e",
  blue: "#3b82f6",
};

const LEAVE_TYPE_NAMES = {
  AL: "Annual / Emergency Leave",
  MC: "Medical Leave",
  HOSP: "Hospitalization Leave",
  PAT: "Paternity Leave",
  MAT: "Maternity Leave",
  COMP_A: "Compassionate Leave A",
  COMP_B: "Compassionate Leave B",
  MAR: "Marriage Leave",
  UNPAID: "Unpaid Leave",
};

function formatDate(d) {
  return new Date(d).toLocaleDateString("en-GB");
}

function leaveType(code) {
  return LEAVE_TYPE_NAMES[code] || code;
}

// ======================================================
// BASE LAYOUT
// ======================================================
function baseLayout(title, subtitle, accentColor, contentHTML) {
  return `
<table width="100%" cellpadding="0" cellspacing="0" style="background:${BRAND.bg}; margin:0; padding:0;">
  <tr><td align="center" style="padding:30px 15px;">
    <table width="600" cellpadding="0" cellspacing="0" style="background:${BRAND.surface}; border-radius:8px; overflow:hidden; box-shadow:0 2px 8px rgba(0,0,0,0.06);">
      <!-- Header -->
      <tr>
        <td style="background:linear-gradient(135deg,${BRAND.primary},${BRAND.navy}); padding:24px 30px; text-align:center;">
          <img src="${LOGO_EFTECH}" width="140" alt="Eftech" style="display:block; margin:0 auto 8px auto;" />
          <img src="${LOGO_MYLEAVE}" width="110" alt="MyLeave" style="display:block; margin:0 auto;" />
        </td>
      </tr>
      <!-- Accent bar -->
      <tr><td style="background:${accentColor}; height:4px;"></td></tr>
      <!-- Title -->
      <tr>
        <td style="padding:30px 36px 0 36px;">
          <h1 style="margin:0; font-size:22px; color:${BRAND.text}; font-weight:700;">${title}</h1>
          <p style="margin:8px 0 0 0; font-size:14px; color:${BRAND.muted};">${subtitle}</p>
        </td>
      </tr>
      <!-- Content -->
      <tr>
        <td style="padding:24px 36px;">
          ${contentHTML}
        </td>
      </tr>
      <!-- Footer -->
      <tr>
        <td style="padding:20px 36px 30px 36px;">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr><td style="border-top:1px solid ${BRAND.border}; padding:0;"></td></tr>
          </table>
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td align="center" style="padding-top:24px;">
                <img src="${LOGO_EFTECH}" width="120" alt="Eftech" style="display:block; margin:0 auto 6px auto; opacity:0.85;" />
                <img src="${LOGO_MYLEAVE}" width="90" alt="MyLeave" style="display:block; margin:0 auto 10px auto; opacity:0.85;" />
                <p style="font-size:11px; color:${BRAND.mutedLight}; margin:0;">This email was automatically generated by <b>MyLeave System</b>.<br/>Please do not reply to this email.</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </td></tr>
</table>`;
}

// ======================================================
// REUSABLE COMPONENTS
// ======================================================
function infoRow(label, value, borderColor) {
  return `
  <tr>
    <td width="130" style="font-size:13px; color:${BRAND.muted}; padding:6px 0; vertical-align:top;">${label}</td>
    <td style="font-size:14px; color:${BRAND.text}; padding:6px 0; vertical-align:top; font-weight:600;">${value}</td>
  </tr>
  <tr><td colspan="2" style="border-top:1px solid ${borderColor}; padding:0;"></td></tr>`;
}

function infoRowLast(label, value, borderColor) {
  return `
  <tr>
    <td width="130" style="font-size:13px; color:${BRAND.muted}; padding:6px 0; vertical-align:top;">${label}</td>
    <td style="font-size:14px; color:${BRAND.text}; padding:6px 0; vertical-align:top; font-weight:600;">${value}</td>
  </tr>`;
}

function statusBadge(text, bgColor) {
  return `<span style="display:inline-block; background:${bgColor}; color:#fff; font-size:12px; font-weight:600; padding:3px 10px; border-radius:12px;">${text}</span>`;
}

function leaveInfoCard(leave, bgColor, borderColor, textColor, statusText, statusBg) {
  const rows = [];
  if (statusText) {
    rows.push(infoRow("Status", statusBadge(statusText, statusBg), borderColor));
  }
  rows.push(infoRow("Type", leaveType(leave.leave_type), borderColor));
  rows.push(infoRow("Date", `${formatDate(leave.date_from)} &rarr; ${formatDate(leave.date_until)}`, borderColor));
  rows.push(infoRowLast("Days", String(leave.total_days), borderColor));

  return `
  <table width="100%" cellpadding="0" cellspacing="0" style="background:${bgColor}; border:1px solid ${borderColor}; border-radius:8px;">
    <tr><td style="padding:20px 24px;">
      <table width="100%" cellpadding="0" cellspacing="0">
        ${rows.join("")}
      </table>
    </td></tr>
  </table>`;
}

function actionButton(url, text) {
  return `
  <table width="100%" cellpadding="0" cellspacing="0" style="margin-top:24px;">
    <tr><td align="center">
      <a href="${url}" target="_blank" style="display:inline-block; background:${BRAND.primary}; color:#ffffff; font-size:15px; font-weight:600; text-decoration:none; padding:12px 36px; border-radius:6px;">${text}</a>
    </td></tr>
  </table>`;
}

// ======================================================
// GENERIC SEND (with error handling)
// ======================================================
async function safeSend(to, subject, content, isText = false) {
  try {
    const payload = {
      from: `"Eftech HR" <${process.env.EMAIL_USER || "no-reply@eftech.com.my"}>`,
      to,
      subject,
    };
    if (isText) {
      payload.text = content;
    } else {
      payload.html = content;
    }
    await getTransporter().sendMail(payload);
    console.log("Email sent to", to);
  } catch (err) {
    console.error("Email failed:", err.message);
  }
}

// ======================================================
// EMAIL TEMPLATE FUNCTIONS
// ======================================================

export function sendLeaveSubmitted(to, staffName, leave) {
  const html = `
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 20px 0;">Hello <b>${staffName}</b>,</p>
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 24px 0;">Your leave request has been submitted successfully and is awaiting approval.</p>
    ${leaveInfoCard(leave, "#f9fafb", BRAND.border, BRAND.text, "Pending", BRAND.blue)}
  `;

  return safeSend(to, "Your Leave Request Has Been Submitted",
    baseLayout("Leave Request Submitted", "Your request is pending manager approval", BRAND.primary, html));
}

export function sendPendingApproval(to, staffName, leave) {
  const html = `
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 8px 0;">Hello <b>Manager</b>,</p>
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 24px 0;"><b>${staffName}</b> has submitted a leave request that requires your approval.</p>
    ${leaveInfoCard(leave, BRAND.amberBg, BRAND.amberBorder, BRAND.amberText, null, null)}
    ${actionButton(BASE_URL, "Review Request")}
  `;

  return safeSend(to, "Pending Leave Approval",
    baseLayout("Pending Leave Approval", "A team member is waiting for your review", BRAND.amber, html));
}

export function sendLeaveApproved(to, leave) {
  const html = `
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 20px 0;">Hello <b>${leave.staff_name || "there"}</b>,</p>
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 24px 0;">Great news! Your leave request has been <b style="color:#16a34a;">approved</b>.</p>
    ${leaveInfoCard(leave, BRAND.greenBg, BRAND.greenBorder, BRAND.greenText, "Approved", BRAND.green)}
  `;

  return safeSend(to, "Your Leave Has Been Approved",
    baseLayout("Leave Approved", "Your leave request has been approved", BRAND.green, html));
}

export function sendLeaveRejected(to, leave) {
  const html = `
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 20px 0;">Hello <b>${leave.staff_name || "there"}</b>,</p>
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 24px 0;">We regret to inform you that your leave request has been <b style="color:#dc2626;">rejected</b>.</p>
    ${leaveInfoCard(leave, BRAND.redBg, BRAND.redBorder, BRAND.redText, "Rejected", BRAND.red)}
  `;

  return safeSend(to, "Your Leave Request Has Been Rejected",
    baseLayout("Leave Rejected", "Your leave request was not approved", BRAND.red, html));
}

export function sendCancellationPending(to, staffName, leave) {
  const html = `
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 8px 0;">Hello <b>Manager</b>,</p>
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 24px 0;"><b>${staffName}</b> has requested to cancel their approved leave.</p>
    ${leaveInfoCard(leave, BRAND.amberBg, BRAND.amberBorder, BRAND.amberText, null, null)}
    ${actionButton(BASE_URL, "Review Request")}
  `;

  return safeSend(to, "Leave Cancellation Request",
    baseLayout("Leave Cancellation Request", "A cancellation request needs your review", BRAND.amber, html));
}

export function sendCancellationApproved(to, leave) {
  const html = `
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 20px 0;">Hello <b>${leave.staff_name || "there"}</b>,</p>
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 24px 0;">Your leave cancellation has been <b style="color:#16a34a;">approved</b>. Your leave balance has been refunded.</p>
    ${leaveInfoCard(leave, BRAND.greenBg, BRAND.greenBorder, BRAND.greenText, "Cancelled", BRAND.green)}
  `;

  return safeSend(to, "Your Leave Cancellation Has Been Approved",
    baseLayout("Cancellation Approved", "Your leave has been cancelled and balance refunded", BRAND.green, html));
}

// ======================================================
// WELCOME / NEW ACCOUNT EMAIL
// ======================================================
export function sendWelcomeEmail(to, { name, email, randomPassword, proratedAnnualLeave, proratedMedicalLeave, yearsOfService, baseAnnualLeave, baseMedicalLeave }) {
  let serviceNote = "";
  if (yearsOfService >= 5) serviceNote = "(16 AL / 22 MC base &ndash; 5+ years service)";
  else if (yearsOfService >= 2) serviceNote = "(14 AL / 18 MC base &ndash; 2&ndash;4 years service)";
  else serviceNote = "(14 AL / 14 MC base &ndash; less than 2 years service)";

  const isProrated = proratedAnnualLeave < baseAnnualLeave || proratedMedicalLeave < baseMedicalLeave;

  const html = `
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 20px 0;">Hello <b>${name}</b>,</p>
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 24px 0;">Your <b>MyLeave</b> account has been created. Here are your login credentials:</p>

    <!-- Credentials -->
    <table width="100%" cellpadding="0" cellspacing="0" style="background:${BRAND.bg}; border:1px solid ${BRAND.border}; border-radius:8px;">
      <tr><td style="padding:20px 24px;">
        <p style="font-size:12px; color:${BRAND.muted}; text-transform:uppercase; letter-spacing:1px; margin:0 0 12px 0; font-weight:600;">Login Credentials</p>
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td width="100" style="font-size:13px; color:${BRAND.muted}; padding:6px 0; vertical-align:top;">Email</td>
            <td style="font-size:14px; color:${BRAND.text}; padding:6px 0; vertical-align:top; font-weight:600;">${email}</td>
          </tr>
          <tr><td colspan="2" style="border-top:1px solid ${BRAND.border}; padding:0;"></td></tr>
          <tr>
            <td style="font-size:13px; color:${BRAND.muted}; padding:6px 0; vertical-align:top;">Password</td>
            <td style="font-size:14px; color:${BRAND.text}; padding:4px 8px; vertical-align:top; font-family:monospace; font-weight:600; background:#fef3c7; border-radius:4px; display:inline-block;">${randomPassword}</td>
          </tr>
        </table>
      </td></tr>
    </table>

    <!-- Entitlements -->
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-top:16px; background:${BRAND.greenBg}; border:1px solid ${BRAND.greenBorder}; border-radius:8px;">
      <tr><td style="padding:20px 24px;">
        <p style="font-size:12px; color:${BRAND.greenText}; text-transform:uppercase; letter-spacing:1px; margin:0 0 12px 0; font-weight:600;">Leave Entitlements</p>
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td style="font-size:14px; color:${BRAND.greenText}; padding:4px 0;">Annual Leave</td>
            <td align="right" style="font-size:14px; color:${BRAND.greenText}; padding:4px 0; font-weight:700;">${proratedAnnualLeave} days</td>
          </tr>
          <tr>
            <td style="font-size:14px; color:${BRAND.greenText}; padding:4px 0;">Medical Leave</td>
            <td align="right" style="font-size:14px; color:${BRAND.greenText}; padding:4px 0; font-weight:700;">${proratedMedicalLeave} days</td>
          </tr>
        </table>
        <p style="font-size:11px; color:${BRAND.muted}; margin:10px 0 0 0;">${serviceNote}${isProrated ? "<br/>(Prorated for joining mid-year)" : ""}</p>
      </td></tr>
    </table>

    <!-- Steps -->
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:24px 0 12px 0; font-weight:600;">Next Steps:</p>
    <table width="100%" cellpadding="0" cellspacing="0">
      <tr>
        <td width="30" style="font-size:14px; color:${BRAND.primary}; padding:6px 0; vertical-align:top; font-weight:700;">1.</td>
        <td style="font-size:14px; color:${BRAND.textSecondary}; padding:6px 0; vertical-align:top;">Go to <a href="${BASE_URL}/login" style="color:${BRAND.primary}; font-weight:600;">MyLeave System</a></td>
      </tr>
      <tr>
        <td style="font-size:14px; color:${BRAND.primary}; padding:6px 0; vertical-align:top; font-weight:700;">2.</td>
        <td style="font-size:14px; color:${BRAND.textSecondary}; padding:6px 0; vertical-align:top;">Log in using the temporary password above</td>
      </tr>
      <tr>
        <td style="font-size:14px; color:${BRAND.primary}; padding:6px 0; vertical-align:top; font-weight:700;">3.</td>
        <td style="font-size:14px; color:${BRAND.textSecondary}; padding:6px 0; vertical-align:top;">Change your password immediately after logging in</td>
      </tr>
    </table>
    <p style="font-size:13px; color:${BRAND.muted}; margin:20px 0 0 0; font-style:italic;">For security reasons, please do not share your login details with anyone.</p>
  `;

  return safeSend(to, "Your MyLeave Account",
    baseLayout("Welcome to MyLeave", "Your account has been created", BRAND.primary, html));
}

// ======================================================
// PASSWORD RESET OTP EMAIL
// ======================================================
export function sendPasswordResetOtp(to, otp) {
  const html = `
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 24px 0;">You requested a password reset. Use the code below to continue:</p>
    <table width="100%" cellpadding="0" cellspacing="0" style="background:${BRAND.bg}; border:2px dashed ${BRAND.primary}; border-radius:8px;">
      <tr><td align="center" style="padding:28px 24px;">
        <p style="font-size:12px; color:${BRAND.muted}; text-transform:uppercase; letter-spacing:2px; margin:0 0 8px 0; font-weight:600;">Your verification code</p>
        <p style="font-size:36px; color:${BRAND.text}; font-weight:800; letter-spacing:10px; margin:0; font-family:'Courier New',monospace;">${otp}</p>
      </td></tr>
    </table>
    <p style="font-size:13px; color:${BRAND.muted}; margin:20px 0 0 0; text-align:center;">This code will expire in <b>10 minutes</b>.</p>
    <p style="font-size:13px; color:#dc2626; margin:12px 0 0 0; text-align:center;">If you did not request this code, please ignore this email.</p>
  `;

  return safeSend(to, "Password Reset Code",
    baseLayout("Password Reset Code", "Use this code to reset your password", BRAND.primary, html));
}

// ======================================================
// EMAIL CORRECTION NOTIFICATION
// ======================================================
export function sendEmailCorrection(to, { name, newEmail }) {
  const html = `
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 20px 0;">Hello <b>${name}</b>,</p>
    <p style="font-size:15px; color:${BRAND.textSecondary}; margin:0 0 24px 0;">Your MyLeave account email has been corrected.</p>
    <table width="100%" cellpadding="0" cellspacing="0" style="background:${BRAND.bg}; border:1px solid ${BRAND.border}; border-radius:8px;">
      <tr><td style="padding:20px 24px;">
        <p style="font-size:12px; color:${BRAND.muted}; text-transform:uppercase; letter-spacing:1px; margin:0 0 12px 0; font-weight:600;">Updated Email</p>
        <p style="font-size:14px; color:${BRAND.text}; margin:0; font-weight:600;">${newEmail}</p>
      </td></tr>
    </table>
    <p style="font-size:14px; color:${BRAND.muted}; margin:20px 0 0 0;">Please use this email to log in to the MyLeave system.</p>
  `;

  return safeSend(to, "Your MyLeave Account – Email Correction",
    baseLayout("Email Corrected", "Your account email has been updated", BRAND.primary, html));
}

// ======================================================
// ADMIN NOTIFICATION (plain text, internal)
// ======================================================
export function sendAdminNotification(to, { name, email, role, position, password, proratedAnnualLeave, proratedMedicalLeave, yearsOfService }) {
  const text = `New employee added:\n\nName: ${name}\nEmail: ${email}\nRole: ${role}\nPosition: ${position}\nPassword: ${password}\n\nLeave Entitlement:\n- Annual Leave: ${proratedAnnualLeave} days (Years of Service: ${yearsOfService})\n- Medical Leave: ${proratedMedicalLeave} days`;

  return safeSend(to, `New employee added: ${name}`, text, true);
}
