import nodemailer from "nodemailer";

// ======================================================
// TRANSPORTER SETUP
// ======================================================
const transporter = nodemailer.createTransport({
  host: "mail.eftech.com.my",
  port: 465,
  secure: true,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

// const transporter = nodemailer.createTransport({
//   host: "localhost",
//   port: 1025,
//   secure: false,
// });

// ======================================================
// HELPER: FORMAT TARIKH DD/MM/YYYY
// ======================================================
function formatDate(dateString) {
  const date = new Date(dateString);
  return date.toLocaleDateString("en-GB"); // dd/mm/yyyy format
}

// ======================================================
// HELPER: FULL LEAVE TYPE NAME
// ======================================================
const leaveTypeFullName = {
  AL: "Annual / Emergency Leave",
  MC: "Medical Leave",
  HOSP: "Hospitalization Leave",
  PAT: "Paternity Leave",
  MAT: "Maternity Leave",
  COMP_A: "Compassionate Leave A",
  COMP_B: "Compassionate Leave B",
  MAR: "Marriage Leave",
  UNPAID: "Unpaid Leave"
};

function getFullLeaveType(code) {
  return leaveTypeFullName[code] || code;
}

// ======================================================
// FOOTER WITH LOGOS
// ======================================================
const EMAIL_FOOTER = `
<br/><br/>
<div style="text-align:center; margin-top:30px; opacity:0.85;">
  <img src="http://edsdata.com.my:3000/static/images/eftech.png"
       style="width:140px; margin-bottom:8px;" />
  <br/>
  <img src="http://edsdata.com.my:3000/static/images/myleave.png"
       style="width:110px; opacity:0.9;" />
  <p style="font-size:11px; color:#666; margin-top:8px;">
    This email was automatically generated by <b>MyLeave System</b>.
  </p>
</div>
`;

// ======================================================
// GENERIC SEND FUNCTION
// ======================================================
async function sendEmail(to, subject, html) {
  try {
    await transporter.sendMail({
      from: `"Eftech HR" <${process.env.EMAIL_USER}>`,
      to,
      subject,
      html
    });

    console.log("📧 Email sent to", to);
  } catch (err) {
    console.error("❌ Email failed:", err);
  }
}

// ======================================================
// EMAIL FUNCTIONS
// ======================================================
export function sendLeaveSubmitted(staffEmail, staffName, leave) {
  return sendEmail(
    staffEmail,
    "Your Leave Request Has Been Submitted",
    `
    <h3>Hello ${staffName},</h3>
    <p>Your leave request has been submitted successfully.</p>

    <p><b>Status:</b> Pending</p>

    <p>
      <b>Type:</b> ${getFullLeaveType(leave.leave_type)}<br/>
      <b>Date:</b> ${formatDate(leave.date_from)} → ${formatDate(leave.date_until)}<br/>
      <b>Days:</b> ${leave.total_days}
    </p>
    

    ${EMAIL_FOOTER}
    `
  );
}

export function sendPendingApproval(managerEmail, staffName, leave) {
  return sendEmail(
    managerEmail,
    "Pending Leave Approval",
    `
    <h3>You have a pending leave request</h3>

    <p><b>From:</b> ${staffName}</p>

    <p>
      <b>Type:</b> ${getFullLeaveType(leave.leave_type)}<br/>
      <b>Date:</b> ${formatDate(leave.date_from)} → ${formatDate(leave.date_until)}<br/>
      <b>Days:</b> ${leave.total_days}
    </p>

    ${EMAIL_FOOTER}
    `
  );
}

export function sendLeaveApproved(staffEmail, leave) {
  return sendEmail(
    staffEmail,
    "Your Leave Has Been Approved 🎉",
    `
    <h3>Your leave has been approved!</h3>

    <p>
      <b>Type:</b> ${getFullLeaveType(leave.leave_type)}<br/>
      <b>Date:</b> ${formatDate(leave.date_from)} → ${formatDate(leave.date_until)}<br/>
      <b>Days:</b> ${leave.total_days}
    </p>

    ${EMAIL_FOOTER}
    `
  );
}

export function sendLeaveRejected(staffEmail, leave) {
  return sendEmail(
    staffEmail,
    "Your Leave Request Has Been Rejected",
    `
    <h3>Your leave request was rejected.</h3>

    <p>
      <b>Type:</b> ${getFullLeaveType(leave.leave_type)}<br/>
      <b>Date:</b> ${formatDate(leave.date_from)} → ${formatDate(leave.date_until)}<br/>
      <b>Days:</b> ${leave.total_days}
    </p>

    ${EMAIL_FOOTER}
    `
  );
}

export function sendCancellationPending(managerEmail, staffName, leave) {
  return sendEmail(
    managerEmail,
    "Leave Cancellation Request Pending",
    `
    <h3>Leave cancellation request received</h3>

    <p><b>From:</b> ${staffName}</p>

    <p>
      <b>Type:</b> ${getFullLeaveType(leave.leave_type)}<br/>
      <b>Original Date:</b> ${formatDate(leave.date_from)} → ${formatDate(leave.date_until)}<br/>
      <b>Days:</b> ${leave.total_days}
    </p>

    ${EMAIL_FOOTER}
    `
  );
}

export function sendCancellationApproved(staffEmail, leave) {
  return sendEmail(
    staffEmail,
    "Your Leave Cancellation Has Been Approved",
    `
    <h3>Your cancellation has been approved.</h3>
    <p>Your leave balance has been refunded.</p>

    ${EMAIL_FOOTER}
    `
  );
}
